### PR TITLE
Null Safety Support

### PR DESCRIPTION
**Pull request by dvaldivia**
This PR simply ran `dart migrate` on both the library and the examples, had to update `image_picker` dependency to `0.7.2`

### CODE REVIEW

**Comment by NGhebreial** [comment]
Thanks! @dvaldivia

**Comment by dvaldivia** [comment]
@NGhebreial no problem! glad to help, looking forward to a new release soon!

**Comment by NGhebreial** [comment]
> @NGhebreial no problem! glad to help, looking forward to a new release soon!

Just published 😄

**Comment by dvaldivia** [comment]
Sweet 😎

**Pull request merged**
